import * as flags from './flags';
import locales from './locales';


const localeFlags = {
  [locales.AFRIKAANS]: flags.ZA,
  [locales.ALBANIAN]: flags.AL,
  [locales.ALGERIAN_ARABIC]: flags.DZ,
  [locales.ARABIC]: flags.SA,
  [locales.ARGENTINIAN_SPANISH]: flags.AR,
  [locales.ARMENIAN]: flags.AM,
  [locales.ASTURIAN]: flags.XX,
  [locales.AUSTRALIAN_ENGLISH]: flags.AU,
  [locales.AZERBAIJANI]: flags.AZ,
  [locales.BASQUE]: flags.XX,
  [locales.BELARUSSIAN]: flags.BY,
  [locales.BENGALI]: flags.BD,
  [locales.BOKMAL]: flags.NO,
  [locales.BOSNIAN]: flags.BA,
  [locales.BRAZILIAN_PORTUGUESE]: flags.BR,
  [locales.BRETON]: flags.XX,
  [locales.BRITISH_ENGLISH]: flags.GB,
  [locales.BULGARIAN]: flags.BG,
  [locales.BURMESE]: flags.MM,
  [locales.CATALAN]: flags.ES_CT,
  [locales.COLOMBIAN_SPANISH]: flags.CO,
  [locales.CR]: flags.HR,
  [locales.CZECH]: flags.CZ,
  [locales.DANISH]: flags.DK,
  [locales.DUTCH]: flags.NL,
  [locales.ENGLISH]: flags.US,
  [locales.ESPERANTO]: flags.XX,
  [locales.ESTONIAN]: flags.EE,
  [locales.FINNISH]: flags.FI,
  [locales.FRENCH]: flags.FR,
  [locales.GAELIC]: flags.GB_SCT,
  [locales.GALICIAN]: flags.ES_GA,
  [locales.GEORGIAN]: flags.GE,
  [locales.GERMAN]: flags.DE,
  [locales.GREEK]: flags.GR,
  [locales.HEBREW]: flags.IL,
  [locales.HINDI]: flags.IN,
  [locales.HUNGARIAN]: flags.HU,
  [locales.ICELANDIC]: flags.IS,
  [locales.IDO]: flags.XX,
  [locales.IGBO]: flags.NG,
  [locales.INDONESIAN]: flags.ID,
  [locales.INTERLINGUA]: flags.XX,
  [locales.IRISH]: flags.IE,
  [locales.ITALIAN]: flags.IT,
  [locales.JAPANESE]: flags.JP,
  [locales.KABYLE]: flags.DZ,
  [locales.KANNADA]: flags.IN,
  [locales.KAZAKH]: flags.KZ,
  [locales.KHMER]: flags.KH,
  [locales.KLINGON]: flags.TLH,
  [locales.KOREAN]: flags.KR,
  [locales.KYRGYZ]: flags.KG,
  [locales.LATVIAN]: flags.LV,
  [locales.LITHUANIAN]: flags.LT,
  [locales.LOWER_SORBIAN]: flags.XX,
  [locales.LUXEMBOURGISH]: flags.LU,
  [locales.MACEDONIAN]: flags.MK,
  [locales.MALAYALAM]: flags.IN,
  [locales.MANDARIN_CHINESE]: flags.CN,
  [locales.MARATHI]: flags.IN,
  [locales.MEXICAN_SPANISH]: flags.MX,
  [locales.MONGOLIAN]: flags.MN,
  [locales.NEPALI]: flags.NP,
  [locales.NICARAGUAN_SPANISH]: flags.NI,
  [locales.NORWEGIAN_NYNORSK]: flags.NO,
  [locales.NORWEGIAN]: flags.NO,
  [locales.OSSETIAN]: flags.XX,
  [locales.PANJABI]: flags.XX,
  [locales.PERSIAN]: flags.IR,
  [locales.POLISH]: flags.PL,
  [locales.PORTUGUESE]: flags.PT,
  [locales.ROMANIAN]: flags.RO,
  [locales.RUSSIAN]: flags.RU,
  [locales.SERBIAN_LATIN]: flags.RS,
  [locales.SERBIAN]: flags.RS,
  [locales.SLOVAK]: flags.SK,
  [locales.SLOVENIAN]: flags.SI,
  [locales.SPANISH]: flags.ES,
  [locales.SWAHILI]: flags.KE,
  [locales.SWEDISH]: flags.SE,
  [locales.TAJIK]: flags.TJ,
  [locales.TAMIL]: flags.IN,
  [locales.TATAR]: flags.RU,
  [locales.TELUGU]: flags.IN,
  [locales.THAI]: flags.TH,
  [locales.TRADITIONAL_CHINESE]: flags.TW,
  [locales.TURKISH]: flags.TR,
  [locales.TURKMEN]: flags.TM,
  [locales.UDMURT]: flags.RU,
  [locales.UKRAINIAN]: flags.UA,
  [locales.UPPER_SORBIAN]: flags.XX,
  [locales.URDU]: flags.PK,
  [locales.UZBEK]: flags.UZ,
  [locales.VENEZUELAN_SPANISH]: flags.VE,
  [locales.VIETNAMESE]: flags.VN,
  [locales.WELSH]: flags.GB_WLS,
  [locales.WESTERN_FRISIAN]: flags.XX,
};


export {
  flags,
  locales,
  localeFlags,
};
