name: Publish NPM package

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Running Publish Build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Publish NPM package
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: "public"
          dry-run: false
          check-version: true
